// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReactDemo.Server.Database;

#nullable disable

namespace ReactDemo.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250708123918_AddRoomTypeImageId")]
    partial class AddRoomTypeImageId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReactDemo.Server.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BedsDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SleepersCapacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RoomType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 750.00m,
                            BedsDescription = "1 Queen bed",
                            Description = "1 Queen bed or 2 Twin beds – 25sqm / 269sqft. Balcony or window. Coastal view",
                            ImageId = 1,
                            Name = "Classic Courtyard",
                            Size = "25 sq m",
                            SleepersCapacity = 2
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 850.00m,
                            BedsDescription = "1 Queen bed",
                            Description = "1 Queen bed or 2 Twin beds – From 32 to 36sqm / From 345 to 388sqft. Window – Juliet balcony. Lateral Sea view/coastal view",
                            ImageId = 2,
                            Name = "Superior",
                            Size = "32 to 36 sq m",
                            SleepersCapacity = 2
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 1075.00m,
                            BedsDescription = "1 Queen bed",
                            Description = "1 Large Queen bed or 2 Twin beds – From 35 to 40sqm / From 377 to 431sqft. Sitting area – Desk. Balcony. Sea view",
                            ImageId = 3,
                            Name = "Deluxe with sea view balcony",
                            Size = "35 to 40 sq m",
                            SleepersCapacity = 2
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 1400.00m,
                            BedsDescription = "1 King bed",
                            Description = "1 King bed or 2 Twin beds – From 45 to 55sqm / From 485 to 582sqft. Sitting area – Desk. Big window – Sea view",
                            ImageId = 4,
                            Name = "Junior Suite",
                            Size = "45 to 55 sq m",
                            SleepersCapacity = 2
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 2100.00m,
                            BedsDescription = "1 King bed",
                            Description = "1 King bed or 2 Twin beds – From 65 to 75sqm / From 700 to 807sqft. Separate sitting area – Desk. Big window – Sea view",
                            ImageId = 5,
                            Name = "Corner Suite",
                            Size = "65 to 75 sq m",
                            SleepersCapacity = 3
                        },
                        new
                        {
                            Id = 6,
                            BasePrice = 2275.00m,
                            BedsDescription = "1 King bed",
                            Description = "1 King bed or 2 Twin beds – From 107 to 120sqm / From 1151 to 1291sqft. Separate living area – Desk. Private terrace – Sea view",
                            ImageId = 6,
                            Name = "Suite Deluxe with Terrace",
                            Size = "107 to 120 sq m",
                            SleepersCapacity = 3
                        },
                        new
                        {
                            Id = 7,
                            BasePrice = 2325.00m,
                            BedsDescription = "1 King bed",
                            Description = "1 King bed – 90sqm / 968sqft. Separate sitting area – Private terrace – Sea view. Private heated infinity plunge pool",
                            ImageId = 7,
                            Name = "Junior Suite sea view with Pool",
                            Size = "90 sq m",
                            SleepersCapacity = 2
                        },
                        new
                        {
                            Id = 8,
                            BasePrice = 2470.00m,
                            BedsDescription = "1 King bed",
                            Description = "1 King or 2 Twin beds – From 85 to 105qm. Separate living area – Desk. Private terrace – Sea view. Private heated infinity plunge pool",
                            ImageId = 8,
                            Name = "Suite Deluxe with Pool",
                            Size = "85 to 105 sq m",
                            SleepersCapacity = 3
                        },
                        new
                        {
                            Id = 9,
                            BasePrice = 2850.00m,
                            BedsDescription = "1 Queen bed",
                            Description = "1 King bed or 2 Twin beds – 105sqm / 1131sqft. Sitting area – Desk. Private terrace or garden – Sea view. Private heated infinity plunge pool",
                            ImageId = 9,
                            Name = "Premium Suite Pool",
                            Size = "105 sq m",
                            SleepersCapacity = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
